CUSTOM_NAME=freeforgeminer
CUSTOM_VERSION=1.0.5
CUSTOM_BUILD=1
CUSTOM_ALGO=forgematrix_v4
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/freeforgeminer/miner.json
CUSTOM_LOG_BASENAME=/var/log/miner/freeforgeminer/miner
